[CHK-2653] feat(wallet): add pipelines for `wallet-event-dispatcher`
pagopa/pagopa-azure-devops pull request #323
Opened 2024-03-29 10:41 UTC by giovanniberti

### List of changes

 * add pipelines for `wallet-event-dispatcher`

### Motivation and context

These pipelines are needed for the new [`pagopa-wallet-event-dispatcher-service`](https://github.com/pagopa/pagopa-wallet-event-dispatcher-service) microservice

### Type of changes

- [x] Add new pipeline
- [ ] Update pipeline configuration
- [ ] Remove pipeline

### :warning: If it's new pipeline with code review have you added pagopa-github-bot -> Role: admin?

- [ ] Yes
- [ ] No

### Other information

---

### If PR is partially applied, why? (reserved to mantainers)

2024-04-03 17:46 UTC, infantesimone requested changes

2024-04-03 17:46 UTC, infantesimone commented on azure-devops/wallet/06_pagopa-wallet-event-dispatcher-service.tf
> +    wallet_token_test_dev           = module.wallet_dev_secrets.values["wallet-token-test-key"].value
are these tokens needed?

2024-04-04 12:52 UTC, giovanniberti commented on azure-devops/wallet/06_pagopa-wallet-event-dispatcher-service.tf
> +    wallet_token_test_dev           = module.wallet_dev_secrets.values["wallet-token-test-key"].value
Nope, removing

2024-04-04 12:58 UTC, giovanniberti commented on azure-devops/wallet/06_pagopa-wallet-event-dispatcher-service.tf
> +    wallet_token_test_dev           = module.wallet_dev_secrets.values["wallet-token-test-key"].value
Removed in 3c3f817

2024-04-04 15:28 UTC, infantesimone approved these changes

2024-04-04 15:39 UTC, infantesimone commented
@diegolagospagopa There are some errors in the terraform plan regarding service connections of wallet domain, unrelated to this PR.
service connections changed?

2024-04-10 08:00 UTC, infantesimone approved these changes

2024-04-10 14:27 UTC, merged